### ISSUE TITLE
在测试环境进行加购，请提供加购过程中的截图。

### ISSUE THREAD

**Issue by Linnzh** [yhrhhhhh/Shopping-website-project#3]
例如：

1. 选择商品（选择了哪个商品？请给出商品链接。它的 SKU 是什么？）
2. 将该商品加入购物车，数量为 2

最后提供你的购物车界面截图。

**Comment by yhrhhhhh** [comment]
1.选择商品
商品（1）
商品名称：24V 25A Battery Charger 0400087 400087 for JLG Universal Replacement
商品链接：https://www.jeeda.net/24v-25a-battery-charger-0400087-400087-for-jlg-universal-replacement
图片介绍：
![1](https://github.com/yhrhhhhh/yhr/assets/163226410/1e3590fb-052a-48bf-abc0-09321a2a9382)
SKU：HP34169-25

商品（2）
商品名称：Filter Kit 24121212 39329602 88171913 for Ingersoll Rand Air Compressor UP5 UP6-5 UP6-15C
商品链接：https://www.jeeda.net/filter-kit-24121212-39329602-88171913-for-ingersoll-rand-air-compressor-up5-up6-5-up6-15c
图片介绍：
![image](https://github.com/yhrhhhhh/yhr/assets/163226410/53aec74a-d7ac-4ea2-9256-763e73a5e009)
SKU：LXFP210820011

2.购物车截图
![3](https://github.com/yhrhhhhh/yhr/assets/163226410/ee18a8b3-2fe0-466a-8ce3-180de5ee054e)
